// =============================================================================
// FlashAttention Accelerator - RTL File List
// Topologically sorted: leaves first, top module last
// Generated by bba-guru-rtl
// =============================================================================
// Leaf modules (no dependencies)
fa_regfile.sv
fa_buffer_mgr.sv
fa_divider.sv
fa_softmax.sv
fa_systolic.sv
// Control modules (depend on leaf modules)
fa_dma.sv
fa_ctrl.sv
// Top module (depends on all)
fa_top.sv
