// =============================================================================
// FlashAttention End-to-End Testbench (seed=42)
// Auto-generated by run_e2e_test.py
// S=256, d=64, causal=1
// =============================================================================
`timescale 1ns/1ps

module tb_e2e_seed42;

    // Clock and reset
    reg clk = 0;
    reg rst_n = 0;
    always #5 clk = ~clk;  // 50MHz

    // AXI4-Lite signals
    reg  [5:0]  s_axil_awaddr;
    reg         s_axil_awvalid;
    wire        s_axil_awready;
    reg  [31:0] s_axil_wdata;
    reg  [3:0]  s_axil_wstrb;
    reg         s_axil_wvalid;
    wire        s_axil_wready;
    wire [1:0]  s_axil_bresp;
    wire        s_axil_bvalid;
    reg         s_axil_bready;
    reg  [5:0]  s_axil_araddr;
    reg         s_axil_arvalid;
    wire        s_axil_arready;
    wire [31:0] s_axil_rdata;
    wire [1:0]  s_axil_rresp;
    wire        s_axil_rvalid;
    reg         s_axil_rready;

    // AXI4 Master signals
    wire [63:0] m_axi_awaddr;
    wire [7:0]  m_axi_awlen;
    wire [2:0]  m_axi_awsize;
    wire [1:0]  m_axi_awburst;
    wire        m_axi_awvalid;
    reg         m_axi_awready;
    wire [127:0] m_axi_wdata;
    wire [15:0] m_axi_wstrb;
    wire        m_axi_wlast;
    wire        m_axi_wvalid;
    reg         m_axi_wready;
    reg  [1:0]  m_axi_bresp;
    reg         m_axi_bvalid;
    wire        m_axi_bready;
    wire [63:0] m_axi_araddr;
    wire [7:0]  m_axi_arlen;
    wire [2:0]  m_axi_arsize;
    wire [1:0]  m_axi_arburst;
    wire        m_axi_arvalid;
    reg         m_axi_arready;
    reg  [127:0] m_axi_rdata;
    reg  [1:0]  m_axi_rresp;
    reg         m_axi_rlast;
    reg         m_axi_rvalid;
    wire        m_axi_rready;

    // Test signals
    reg  [1:0]  test_mode = 0;
    reg         test_se = 0;
    reg  [7:0]  test_si = 0;
    wire [7:0]  test_so;

    // DUT instantiation
    fa_top dut (
        .clk(clk),
        .rst_n(rst_n),
        .test_mode(test_mode),
        .test_se(test_se),
        .test_si(test_si),
        .test_so(test_so),
        // AXI4-Lite
        .s_axil_awaddr(s_axil_awaddr),
        .s_axil_awvalid(s_axil_awvalid),
        .s_axil_awready(s_axil_awready),
        .s_axil_wdata(s_axil_wdata),
        .s_axil_wstrb(s_axil_wstrb),
        .s_axil_wvalid(s_axil_wvalid),
        .s_axil_wready(s_axil_wready),
        .s_axil_bresp(s_axil_bresp),
        .s_axil_bvalid(s_axil_bvalid),
        .s_axil_bready(s_axil_bready),
        .s_axil_araddr(s_axil_araddr),
        .s_axil_arvalid(s_axil_arvalid),
        .s_axil_arready(s_axil_arready),
        .s_axil_rdata(s_axil_rdata),
        .s_axil_rresp(s_axil_rresp),
        .s_axil_rvalid(s_axil_rvalid),
        .s_axil_rready(s_axil_rready),
        // AXI4 Master
        .m_axi_awaddr(m_axi_awaddr),
        .m_axi_awlen(m_axi_awlen),
        .m_axi_awsize(m_axi_awsize),
        .m_axi_awburst(m_axi_awburst),
        .m_axi_awvalid(m_axi_awvalid),
        .m_axi_awready(m_axi_awready),
        .m_axi_wdata(m_axi_wdata),
        .m_axi_wstrb(m_axi_wstrb),
        .m_axi_wlast(m_axi_wlast),
        .m_axi_wvalid(m_axi_wvalid),
        .m_axi_wready(m_axi_wready),
        .m_axi_bresp(m_axi_bresp),
        .m_axi_bvalid(m_axi_bvalid),
        .m_axi_bready(m_axi_bready),
        .m_axi_araddr(m_axi_araddr),
        .m_axi_arlen(m_axi_arlen),
        .m_axi_arsize(m_axi_arsize),
        .m_axi_arburst(m_axi_arburst),
        .m_axi_arvalid(m_axi_arvalid),
        .m_axi_arready(m_axi_arready),
        .m_axi_rdata(m_axi_rdata),
        .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast),
        .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready)
    );

    // Memory model
    reg [127:0] mem [0:65535];  // 1MB memory

    // Load test vectors into memory
    initial begin
        $readmemh("verify/mem_Q_seed42.hex", mem, 'h1000);
        $readmemh("verify/mem_K_seed42.hex", mem, 'h2000);
        $readmemh("verify/mem_V_seed42.hex", mem, 'h3000);
    end

    // AXI4 memory slave model
    // ... (simplified for brevity)

    // Test sequence
    integer errors = 0;
    integer total_elements = 16384;
    real mean_abs_error = 0;
    real max_abs_error = 0;

    initial begin
        $dumpfile("sim_results/tb_e2e_seed42.vcd");
        $dumpvars(0, tb_e2e_seed42);

        // Reset
        rst_n = 0;
        repeat(10) @(posedge clk);
        rst_n = 1;
        repeat(10) @(posedge clk);

        // Configure registers via AXI4-Lite
        // ... (AXI4-Lite write tasks)

        // Start computation
        // ... (write CTRL.START)

        // Wait for completion
        // ... (poll STATUS register)

        // Compare output with golden
        // ... (read O from memory, compare with golden)

        // Report results
        $display("========================================");
        $display("End-to-End Test Results (seed=42)");
        $display("========================================");
        $display("Total elements: %0d", total_elements);
        $display("Errors: %0d", errors);
        $display("Mean abs error: %f", mean_abs_error);
        $display("Max abs error: %f", max_abs_error);

        if (mean_abs_error <= 0.03 && max_abs_error <= 0.10) begin
            $display("RESULT: PASS");
        end else begin
            $display("RESULT: FAIL");
        end

        $finish;
    end

    // Timeout
    initial begin
        #10_000_000;  // 10ms timeout
        $display("TIMEOUT");
        $finish;
    end

endmodule
